---
title: "Noah Christensen's CV"
author: Noah Christensen
date: "`r Sys.Date()`"
output:
  pagedown::html_resume:
    css: ['custom_resume.css']
    self_contained: true
knit: pagedown::chrome_print
---
```{r include=FALSE}
library(pagedown)
library(icons)
library(fontawesome)
```

Aside
================================================================================



Contact Info {#contact}
--------------------------------------------------------------------------------

- <i class="fas fa-envelope"></i> noahjchristensen5@gmail.com
- <i class="fab fa-github"></i> [github.com/noahjc26](https://github.com/noahjc26)
- <i class="fas fa-home"></i> 801-376-4084

Skills {#skills}
--------------------------------------------------------------------------------

- #### <i class="fas fa-laptop"></i> Computational:

  - **R**
	- **Python**
	- **EXCEL**
	- **ArcGIS**
	- **QGIS**

<br>

- #### <i class="fas fa-user"></i> Soft:

  - **Communication**
  - **Team Collaboration**
  - **Problem Solving**
  - **Critical Thinking**
  - **Time Management**






Main
================================================================================

Noah Christensen {#title}
--------------------------------------------------------------------------------

Pleasant Grove, UT

--------------------------------------------------------------------------------



Education {data-icon=graduation-cap data-concise=true}
--------------------------------------------------------------------------------

### Utah Valley University

B.S. in Geology

Orem, UT

2024 - 2019

<br>

### Utah Valley University

GIS Certificate

Orem, UT

2024 - 2022

<br>


Work Experience {data-icon=briefcase} 
--------------------------------------------------------------------------------

### SVT Advantage

Customer support, digital marketing, production

Orem, UT

current - 2020


<br>

### Custodian

Alpine School District

Mt. Mahogany ELEM,
PG HS

2020 - 2017

<br>

<br>

Research and Extracurricular {data-icon=chalkboard-teacher}
--------------------------------------------------------------------------------

### Earth Science Student Association President

Event planning, leadership management

UVU

2024 - 2023


<br>

### Remote Sensing Mineral Spectroscopy 

Hydrothermal alteration mapping using ASTER and Landsat 8 imagery in the Marysvale Volcanics Field

N/A

2024 - 2023

<br>

### Isotope Ground Beetle Analysis

Stable isotope analysis on ground beetles collected in Provo Canyon for diet reconstruction

N/A

2024 - 2023

<br>

<br>


```{css, echo=FALSE}

.extra-sidebar h1 {
  display: none;
}

.extra-sidebar .level2:first-of-type {
  margin-top: 0;
}

.main {
  display: block;
  max-width: 40%;  /* Adjust the maximum width as needed */
  margin-left: auto;
  margin-right: auto;
}
```

Second page sidebar {.aside .extra-sidebar}
================================================================================
