---
title: "Final Project"
author: "Noah Christensen"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### packages used

```{r warning=FALSE, message=FALSE, echo=TRUE}
library(raster)
library(terra)
library(tidyverse)
library(janitor)
library(plotly)
library(cowplot)
library(prismatic)
library(stringr)
library(tmap)
library(mapedit)
library(rpart)
library(rpart.plot)
library(rasterVis)
library(mapview)
library(caret)
library(forcats)
```

___

# HYPERION
___

### Inserting spectral library from USGS

```{r echo=TRUE, warning=FALSE}
#reading in spectral mineral signatures
minerals <- list.files(path="../../usgs_spectral_library/usgs_splib07 (1)/ASCIIdata/ASCIIdata_splib07b_cvHYPERION/ChapterM_Minerals/", full.names=TRUE)

#list applying as csv and into a data frame
minerals <- minerals %>% 
  lapply(read.csv) %>% 
  as.data.frame() %>% 
  clean_names() %>% 
  mutate(Bands = row_number())

#removing non-working bands
minerals <- minerals[c(8:57,77:224),]
```

Download Hyperion in L1T product in geotiff format


